image: node:latest

stages:
  - publish

build:
  stage: publish
  script:
    - yarn
    - yarn export
    - rm -rf public
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - main
