import { useState } from "react"
import Head from "next/head"
import { Form, Header, Sidebar } from "../components"

export default function Home() {
  const [IsSidebarOpen, setIsSidebarOpen] = useState(false)

  const toggleSidebar = () => {
    setIsSidebarOpen((IsSidebarOpen) => !IsSidebarOpen)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header toggleSidebar={toggleSidebar} />
        <Sidebar isSidebarOpen={IsSidebarOpen} />
      </main>
    </div>
  )
}
